build:
    environment:
            php:
                version: 8.1.6
            postgresql: true
    tests:
        override:
            -
                command: 'vendor/bin/phpunit tests/Domain'

    nodes:
        analysis:
            dependencies:
                after:
                    - composer require --dev squizlabs/php_codesniffer:4.0.x-dev

            tests:
                override:
                    -
                        command: phpcs-run --standard=PSR12 src tests
                        use_website_config: false
                    - php-scrutinizer-run
