Simara\Cart\Domain\Cart:
  type: entity

  id:
    id:
      type: string

  manyToMany:
    items:
      cascade: [all]
      targetEntity: Item
      joinTable:
        name: cart_item
        joinColumns:
          cart_id:
            referencedColumnName: id
            onDelete: CASCADE
        inverseJoinColumns:
          item_id:
            referencedColumnName: generatedId
            onDelete: CASCADE
